--- john_sample/Makefile	2013-03-10 17:45:50.343332541 -0700
+++ Makefile	2013-03-10 17:53:14.727314090 -0700
@@ -145,6 +145,7 @@
 
 CUDA_OBJS = \
 	cuda_common.o \
+	cuda_cryptsha3_fmt.o cuda_cryptsha3.o \
 	cuda_cryptmd5_fmt.o cuda_cryptmd5.o \
 	cuda_phpass_fmt.o cuda_phpass.o \
 	cuda_cryptsha256_fmt.o cuda_cryptsha256.o \
@@ -1441,6 +1442,12 @@
 cuda_common.o:	cuda/cuda_common.cuh cuda/cuda_common.cu
 	cd cuda; nvcc $(NVCC_FLAGS) cuda_common.cu -o ../cuda_common.o
 
+cuda_cryptsha3.o:  cuda_cryptsha3.h cuda/cryptsha3.cu cuda_common.o
+        cd cuda; nvcc $(NVCC_FLAGS) cryptsha3.cu -o ../cuda_cryptsha3.o
+
+cuda_cryptsha3_fmt.o:  cuda_cryptsha3.o cuda_cryptsha3_fmt.c
+        $(CC)  $(CFLAGS) cuda_cryptsha3_fmt.c -o cuda_cryptsha3_fmt.o
+
 cuda_cryptmd5.o:  cuda_cryptmd5.h cuda/cryptmd5.cu cuda_common.o
 	cd cuda; nvcc $(NVCC_FLAGS) cryptmd5.cu -o ../cuda_cryptmd5.o
 
